project:
  type: website
  output-dir: docs
  
website:
  title: "Amanda Huensch"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: TestP
      - research.qmd
      - href: Huensch_CV.pdf
        text: CV
        target: _blank
    tools:
      - icon: github
        href: https://github.com/huensch/AmandaHuensch
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Amanda Huensch"

format:
  html:
    theme: sandstone
    toc: true

editor: source

