---
title: "Publications"
description-meta: "Information, pdfs, and social metrics of papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
---

Note: \* graduate student co-author

- [Google Scholar](https://scholar.google.com/citations?user=HMwqhe8AAAAJ&hl=en&oi=ao){target="_blank"}

## Journal Articles

\*Chau, T., and **Huensch, A.** (2025). The relationships among L2 fluency, intelligibility, comprehensibility, and accentedness: A meta-analysis. *Studies in Second Language Acquisition*. [https://doi.org/10.1017/S0272263125000014](https://doi.org/10.1017/S0272263125000014){target="_blank"}

**data, materials, and analysis code**: [https://osf.io/dtp8z/](https://osf.io/dtp8z/){target="_blank"}

<center><hr style="width:50%"></center>

Tracy-Ventura, N., **Huensch, A.**, Katz, J., & Mitchell, R. (2025). Is L2 attrition inevitable after instruction ends? An exploratory longitudinal study of advanced instructed L2 users. *Language Learning, 75*, 42-76. [https://doi.org/10.1111/lang.12665](https://doi.org/10.1111/lang.12665){target="_blank"}

**data and analysis code**: [https://osf.io/sypbn/](https://osf.io/sypbn/){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.** (2024). Clarifying the role of inhibitory control in L2 phonological processing: A preregistered, close replication of Darcy et al. (2016). *Studies in Second Language Acquisition, 46*, 1392-1412. [https://doi.org/10.1017/S0272263124000238]( https://doi.org/10.1017/S0272263124000238){target="_blank"}

**data, materials, and analysis code**: [https://osf.io/fxzvj/](https://osf.io/fxzvj/){target="_blank"}

**preregistration**: [https://osf.io/w4gj2](https://osf.io/w4gj2){target="_blank"}

**Award**: [2024 IRIS Replication Award](https://www.iris-database.org/replication-award/)  

<center><hr style="width:50%"></center>

Al-Hoorie, A., Cinaglia, C., Hiver, P., **Huensch, A.**, Isbell, D., Leung, C., & Sudina, E. (2024). Open science: Considerations and issues for TESOL Research. *TESOL Quarterly, 58*, 537-556. [https://doi.org/10.1002/tesq.3304](https://doi.org/10.1002/tesq.3304){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.** (2023). Effects of speaking task and proficiency on the mid-clause pausing characteristics of L1 and L2 speech from the same speakers. *Studies in Second Language Acquisition, 45*, 1031-1055. [https://doi.org/10.1017/S0272263123000323](https://doi.org/10.1017/S0272263123000323){target="_blank"}

**data and analysis code**: [https://osf.io/dn6v3/](https://osf.io/dn6v3/){target="_blank"}

<center><hr style="width:50%"></center>

Brown, D., Fernandez, J., **Huensch, A.** (2023). The role of pragmatic markers in perceptions of L2 fluency in dialogue. *System, 119*, 103157. [https://doi.org/10.1016/j.system.2023.103157]( https://doi.org/10.1016/j.system.2023.103157){target="_blank"}

**data and analysis code**: [https://osf.io/yb8dk/](https://osf.io/yb8dk/){target="_blank"}

<center><hr style="width:50%"></center>

Nagle, C., **Huensch, A.**, & Zárate-Sández, G. (2023). Exploring phonetic predictors of intelligibility, comprehensibility, and foreign accent in L2 Spanish speech. *Modern Language Journal, 107*, 202-221. [https://doi.org/10.1111/modl.12827]( https://doi.org/10.1111/modl.12827){target="_blank"}

**data and analysis code**: [https://osf.io/m2r49/](https://osf.io/m2r49/){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.**, & Nagle, C. (2023). Revisiting the moderating effect of speaker proficiency on the relationships among intelligibility, comprehensibility, and accentedness in L2 Spanish. *Studies in Second Language Acquisition, 45*, 571-585. [https://doi.org/10.1017/S0272263122000213]( https://doi.org/10.1017/S0272263122000213){target="_blank"}

**data and analysis code**: [https://osf.io/4p7r8/](https://osf.io/4p7r8/){target="_blank"}

<center><hr style="width:50%"></center>

Liu, M., Chong, S. W., Marsden, E., McManus, K., Morgan-Short, K., Al-Hoorie, A. H., Plonsky, L., Bolibaugh, C., Hiver, P., Winke, P., **Huensch, A.**, & Hui, B. (2023). Open scholarship in applied linguistics: What, why, and how. *Language Teaching, 56*, 432-437. [https://doi.org/10.1017/S0261444822000349]( https://doi.org/10.1017/S0261444822000349){target="_blank"}

<center><hr style="width:50%"></center>

\*Chau, T., **Huensch, A.**, Hoang, Y. K., & Chau, H. T. (2022). The effects of L2 pronunciation instruction on EFL learners’ intelligibility and fluency in spontaneous speech. [*TESOL-EJ*](https://tesl-ej.org/wordpress/issues/volume25/ej100/ej100a7/){target="_blank"}, *25*(4).

<center><hr style="width:50%"></center>

**Huensch, A.**, & Nagle, C. (2021). The effect of speaker proficiency on intelligibility, comprehensibility, and accentedness in L2 Spanish: A conceptual replication. *Language Learning, 72*, 626-668. [https://doi.org/10.1111/lang.12451]( https://doi.org/10.1111/lang.12451){target="_blank"}

**data, materials, and analysis code**: [https://osf.io/4j5cr/](https://osf.io/4j5cr/){target="_blank"}

**preregistration**: [https://osf.io/h592g](https://osf.io/h592g){target="_blank"}

**Award**: [2022 IRIS Replication Award](https://www.iris-database.org/replication-award/)  

<center><hr style="width:50%"></center>

Nagle, C. L., & **Huensch, A.** (2020). Expanding the scope of L2 intelligibility research: Intelligibility, comprehensibility, and accentedness in L2 Spanish. Journal of Second Language Pronunciation, 6, 329-351. [https://doi.org/10.1075/jslp.20009.nag](https://doi.org/10.1075/jslp.20009.nag){target="_blank"}

<center><hr style="width:50%"></center>

Mitchell, R., Tracy-Ventura, N., & **Huensch, A.** (2020). After study abroad: The maintenance of multilingual identity among anglophone languages graduates. *Modern Language Journal, 104*, 327-344. [https://doi.org/10.1111/modl.12636](https://doi.org/10.1111/modl.12636){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.** (2019). The pronunciation teaching practices of university-level graduate teaching assistants of French and Spanish introductory language courses. *Foreign Language Annals, 52*, 13-31. [https://doi.org/10.1111/flan.12372](https://doi.org/10.1111/flan.12372){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.**, Tracy-Ventura, N., Bridges, J., & Cuesta-Medina, J. (2019). Variables affecting the maintenance of L2 proficiency and fluency four years post-study abroad. *Study Abroad Research in Second Language Acquisition and International Education, 4*, 96-125. [https://doi.org/10.1075/sar.17015.hue](https://doi.org/10.1075/sar.17015.hue){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.** (2019). Pronunciation in foreign language classrooms: Instructors’ training, classroom practices, and beliefs. *Language Teaching Research, 23*, 745-764. [https://doi.org/10.1177/1362168818767182](https://doi.org/10.1177/1362168818767182){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.**, & Thompson, A. S. (2017). Contextualizing attitudes toward pronunciation: Foreign language learners in the US. *Foreign Language Annals, 50*, 410-432. [https://doi.org/10.1111/flan.12259](https://doi.org/10.1111/flan.12259){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.**, & Tracy-Ventura, N. (2017). L2 utterance fluency development before, during, and after residence abroad: A multidimensional investigation. *Modern Language Journal, 101*, 275-293. [https://doi.org/10.1111/modl.12395]( https://doi.org/10.1111/modl.12395){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.**, & Tracy-Ventura, N. (2017). Understanding L2 fluency behavior: The effects of individual differences in L1 fluency, cross-linguistic differences, and proficiency over time. *Applied Psycholinguistics, 38*, 755-785. [https://doi.org/10.1017/S0142716416000424]( https://doi.org/10.1017/S0142716416000424){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.** (2017). How the initiation and resolution of repair sequences act as a device for the co-construction of membership and identity. *Pragmatics and Society, 8*, 355-376. [https://doi.org/10.1075/ps.8.3.02hue]( https://doi.org/10.1075/ps.8.3.02hue){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.** (2016). Perceptual phonetic training improves production in larger discourse contexts. *Journal of Second Language Pronunciation, 2*, 183-207. [https://doi.org/10.1075/jslp.2.2.03hue]( https://doi.org/10.1075/jslp.2.2.03hue){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.**, & Tremblay, A. (2015). Effects of perceptual phonetic training on the perception and production of second language syllable structure. *Journal of Phonetics, 52*, 105-120. [https://doi.org/10.1016/j.wocn.2015.06.007]( https://doi.org/10.1016/j.wocn.2015.06.007){target="_blank"}

<center><hr style="width:50%"></center>

Kim, J., Chim, Y., **Huensch, A.**, Jun, H., Li, H., & Roullion, V. (2010). A case study on an item writing process: Use of test specifications, nature of group dynamics, and individual item writers’ characteristics. *Language Assessment Quarterly, 7*, 160-174. [https://doi.org/10.1080/15434300903473989](https://doi.org/10.1080/15434300903473989){target="_blank"}

<center><hr style="width:50%"></center>

Yoon, S., Pierce, L., **Huensch, A.**, Juul, E., Perkins, S., Sproat, R., & Hasegawa-Johnson, M. (2009). Construction of a rated speech corpus of L2 learners' speech. *CALICO Journal, 26*, 662-673. [pdf](/files/Yoon_etal2009.pdf){target="_blank"}

<center><hr style="width:50%"></center>

## Book Chapters

\*Leal-Arenas, S., and **Huensch, A.** (accepted). Using Memoji facial gestures to enhance L2 word stress perception. In E. Tergujeff & A. Kirkova-Naskova (Eds.), *Achievements in L2 Pronunciation*. Cambridge University Press.

<center><hr style="width:50%"></center>

**Huensch, A.** (2025). Corpus research in L2 phonetics and phonology. In J. Levis, A. Huensch, C. Nagle, & M. Munro (Eds.), *Phonetics and Phonology section of the Encyclopedia of Applied Linguistics*. Carol Chapelle, Editor in chief. Wiley Blackwell.

<center><hr style="width:50%"></center>

\*Leal-Arena, S., & **Huensch, A.** (2024). Do you see what I mean? Cue clashing in L2 Spanish lexical stress perception. In D. J. Olson, J. L. Sturm, O. Dmitrieva, & J. M. Levis (Eds.), *Proceedings of the 14th Pronunciation in Second Language Learning and Teaching Conference* (pp. 1–11). Purdue University. [https://doi.org/10.31274/psllt.170533](https://doi.org/10.31274/psllt.17053){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.** (2024). Open science and preregistration. In L. Plonsky (Ed.), *Open Science in Applied Linguistics* (pp. 132-147). Applied Linguistics Press. [https://www.appliedlinguisticspress.org/home/catalog/plonsky_2024](https://www.appliedlinguisticspress.org/home/catalog/plonsky_2024){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.**, & Staples, S. (2022). Spoken corpora. In T. Derwing, M. Munro, & R. Thomson (Eds.), *Handbook of SLA and Speaking* (pp. 112-129). Routledge. [pdf](/files/Huensch_Staples2022.pdf){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.** (2021). Fluency. In N. Tracy-Ventura & M. Paquot (Eds.), *The Routledge Handbook of SLA and Corpora* (pp. 293-304). Routledge. [pdf](/files/Huensch2021.pdf){target="_blank"}

<center><hr style="width:50%"></center>

Tracy-Ventura, N., **Huensch, A.**, Mitchell, R. (2021). Understand the long-term evolution of L2 lexical diversity: The contribution of a longitudinal learner corpus. In B. Le Bruyn & M. Paquot (Eds.), *Learner Corpora and Second Language Acquisition*. Cambridge University Press. [pdf](/files/TracyVentura_Huensch_Mitchell2021.pdf){target="_blank"}

<center><hr style="width:50%"></center>

Ghanem, R., Edalatishams, I., **Huensch, A.**, Puga, K., & Staples, S. (2020). The effectiveness of computer programs in the transcription and analysis of spoken discourse: Towards a protocol for pronunciation corpora. In O. Kang, S. Staples, K. Yaw, & K. Hirschi (Eds.), *Proceedings of the 11th Pronunciation in Second Language Learning and Teaching conference* (ISSN 2380-9566) (pp. 97-114)¬. Iowa State University. [https://www.iastatedigitalpress.com/psllt/article/id/15416/](https://www.iastatedigitalpress.com/psllt/article/id/15416/){target="_blank"}

<center><hr style="width:50%"></center>

**Huensch, A.** (2018). Examining foreign language instructors’ definitions of pronunciation instruction. In J. Levis (Ed.), *Proceedings of the 9th Pronunciation in Second Language Learning and Teaching Conference* (ISSN 2380-9566) (pp. 100-110). Iowa State University. [https://www.iastatedigitalpress.com/psllt/article/id/15345/](https://www.iastatedigitalpress.com/psllt/article/id/15345/){target="_blank"}

<center><hr style="width:50%"></center>

Tracy-Ventura, N., & **Huensch, A.** (2018). The potential of publicly shared longitudinal learner corpora in SLA research. In A. Gudmestad & A. Edmonds (Eds.), *Critical Reflections on Data in Second Language Acquisition* (pp. 149–170). John Benjamins. [pdf](/files/TracyVentura_Huensch2018.pdf){target="_blank"}

<center><hr style="width:50%"></center>

Thompson, A. S., & **Huensch, A.** (2017). Pronunciation attitudes: The role of multilingual status and perceived positive language interaction (PPLI). In M. O’Brien & J. Levis (Eds.), *Proceedings of the 8th Pronunciation in Second Language Learning and Teaching Conference* (ISSN 2380-9566) (pp. 144-154). Iowa State University. [https://www.iastatedigitalpress.com/psllt/article/id/15319/](https://www.iastatedigitalpress.com/psllt/article/id/15319/){target="_blank"}

<center><hr style="width:50%"></center>

Watts, P., & **Huensch, A.** (2015). Assessing assessment: A principled revision of an in-house pronunciation diagnostic test. In J. Levis, R. Mohammed, M. Qian & Z. Zhou (Eds.), *Proceedings of the 6th Pronunciation in Second Language Learning and Teaching Conference* (pp. 253-261). Iowa State University. [https://www.iastatedigitalpress.com/psllt/article/id/15266/](https://www.iastatedigitalpress.com/psllt/article/id/15266/){target="_blank"}

<center><hr style="width:50%"></center>

Watts, P., & **Huensch, A.** (2013). Integrated speaking, listening and pronunciation: Are textbooks leading the way? In J. Levis & K. LeVelle (Eds.), *Proceedings of the 4th Pronunciation in Second Language Learning and Teaching Conference* (pp. 265-278). Iowa State University. [https://www.iastatedigitalpress.com/psllt/article/id/15221/](https://www.iastatedigitalpress.com/psllt/article/id/15221/){target="_blank"}

<center><hr style="width:50%"></center>

Lichtman, K., Chang, S., Cramer, J., Crespo del Rio, C., Hallett, J., **Huensch, A.**, & Morales, A. (2010). IPA illustration of Q'anjob'al. *Studies in the Linguistic Sciences: Illinois Working Papers 2010*: 1-23. [https://www.ideals.illinois.edu/items/17170](https://www.ideals.illinois.edu/items/17170){target="_blank"}

<center><hr style="width:50%"></center>

